// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pkg/cluster/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerState int32

const (
	PeerState_PEER_STATE_UNSPECIFIED    PeerState = 0
	PeerState_PEER_STATE_HEALTHY        PeerState = 1
	PeerState_PEER_STATE_SUSPECTED_DEAD PeerState = 2
	PeerState_PEER_STATE_DEAD           PeerState = 3
)

// Enum value maps for PeerState.
var (
	PeerState_name = map[int32]string{
		0: "PEER_STATE_UNSPECIFIED",
		1: "PEER_STATE_HEALTHY",
		2: "PEER_STATE_SUSPECTED_DEAD",
		3: "PEER_STATE_DEAD",
	}
	PeerState_value = map[string]int32{
		"PEER_STATE_UNSPECIFIED":    0,
		"PEER_STATE_HEALTHY":        1,
		"PEER_STATE_SUSPECTED_DEAD": 2,
		"PEER_STATE_DEAD":           3,
	}
)

func (x PeerState) Enum() *PeerState {
	p := new(PeerState)
	*p = x
	return p
}

func (x PeerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerState) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_cluster_messages_proto_enumTypes[0].Descriptor()
}

func (PeerState) Type() protoreflect.EnumType {
	return &file_pkg_cluster_messages_proto_enumTypes[0]
}

func (x PeerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerState.Descriptor instead.
func (PeerState) EnumDescriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{0}
}

type GossipMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcId         string                 `protobuf:"bytes,1,opt,name=srcId,proto3" json:"srcId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessageEnvelope) Reset() {
	*x = GossipMessageEnvelope{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessageEnvelope) ProtoMessage() {}

func (x *GossipMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessageEnvelope.ProtoReflect.Descriptor instead.
func (*GossipMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GossipMessageEnvelope) GetSrcId() string {
	if x != nil {
		return x.SrcId
	}
	return ""
}

type GossipHeartbeatMessage struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	TsUnixNano       int64                   `protobuf:"varint,1,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	VersionMapDigest map[string]*DigestEntry `protobuf:"bytes,2,rep,name=version_map_digest,json=versionMapDigest,proto3" json:"version_map_digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GossipHeartbeatMessage) Reset() {
	*x = GossipHeartbeatMessage{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipHeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipHeartbeatMessage) ProtoMessage() {}

func (x *GossipHeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipHeartbeatMessage.ProtoReflect.Descriptor instead.
func (*GossipHeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GossipHeartbeatMessage) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

func (x *GossipHeartbeatMessage) GetVersionMapDigest() map[string]*DigestEntry {
	if x != nil {
		return x.VersionMapDigest
	}
	return nil
}

type GossipDiffMessage struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	StateDelta       map[string]*GossipVersionedState `protobuf:"bytes,1,rep,name=state_delta,json=stateDelta,proto3" json:"state_delta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	VersionMapDigest map[string]*DigestEntry          `protobuf:"bytes,2,rep,name=version_map_digest,json=versionMapDigest,proto3" json:"version_map_digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GossipDiffMessage) Reset() {
	*x = GossipDiffMessage{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDiffMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDiffMessage) ProtoMessage() {}

func (x *GossipDiffMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDiffMessage.ProtoReflect.Descriptor instead.
func (*GossipDiffMessage) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GossipDiffMessage) GetStateDelta() map[string]*GossipVersionedState {
	if x != nil {
		return x.StateDelta
	}
	return nil
}

func (x *GossipDiffMessage) GetVersionMapDigest() map[string]*DigestEntry {
	if x != nil {
		return x.VersionMapDigest
	}
	return nil
}

type GossipDeltaMessage struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	StateDelta    map[string]*GossipVersionedState `protobuf:"bytes,1,rep,name=state_delta,json=stateDelta,proto3" json:"state_delta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipDeltaMessage) Reset() {
	*x = GossipDeltaMessage{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDeltaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDeltaMessage) ProtoMessage() {}

func (x *GossipDeltaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDeltaMessage.ProtoReflect.Descriptor instead.
func (*GossipDeltaMessage) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GossipDeltaMessage) GetStateDelta() map[string]*GossipVersionedState {
	if x != nil {
		return x.StateDelta
	}
	return nil
}

type GossipVersionedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DigestEntry   *DigestEntry           `protobuf:"bytes,1,opt,name=digest_entry,json=digestEntry,proto3" json:"digest_entry,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipVersionedState) Reset() {
	*x = GossipVersionedState{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipVersionedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipVersionedState) ProtoMessage() {}

func (x *GossipVersionedState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipVersionedState.ProtoReflect.Descriptor instead.
func (*GossipVersionedState) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GossipVersionedState) GetDigestEntry() *DigestEntry {
	if x != nil {
		return x.DigestEntry
	}
	return nil
}

func (x *GossipVersionedState) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DigestEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Address          string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	LastSeenUnixNano int64                  `protobuf:"varint,3,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	PeerState        PeerState              `protobuf:"varint,4,opt,name=peer_state,json=peerState,proto3,enum=PeerState" json:"peer_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DigestEntry) Reset() {
	*x = DigestEntry{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestEntry) ProtoMessage() {}

func (x *DigestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestEntry.ProtoReflect.Descriptor instead.
func (*DigestEntry) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{5}
}

func (x *DigestEntry) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DigestEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DigestEntry) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

func (x *DigestEntry) GetPeerState() PeerState {
	if x != nil {
		return x.PeerState
	}
	return PeerState_PEER_STATE_UNSPECIFIED
}

// Request/Response wrappers that include envelope metadata and hash
type GossipHeartbeatRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Envelope         *GossipMessageEnvelope  `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	HeartbeatMessage *GossipHeartbeatMessage `protobuf:"bytes,2,opt,name=heartbeat_message,json=heartbeatMessage,proto3" json:"heartbeat_message,omitempty"`
	Hash             string                  `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // Message integrity hash
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GossipHeartbeatRequest) Reset() {
	*x = GossipHeartbeatRequest{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipHeartbeatRequest) ProtoMessage() {}

func (x *GossipHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*GossipHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{6}
}

func (x *GossipHeartbeatRequest) GetEnvelope() *GossipMessageEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GossipHeartbeatRequest) GetHeartbeatMessage() *GossipHeartbeatMessage {
	if x != nil {
		return x.HeartbeatMessage
	}
	return nil
}

func (x *GossipHeartbeatRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GossipDiffResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Envelope          *GossipMessageEnvelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	GossipDiffMessage *GossipDiffMessage     `protobuf:"bytes,2,opt,name=gossip_diff_message,json=gossipDiffMessage,proto3" json:"gossip_diff_message,omitempty"`
	Hash              string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // Message integrity hash
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GossipDiffResponse) Reset() {
	*x = GossipDiffResponse{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDiffResponse) ProtoMessage() {}

func (x *GossipDiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDiffResponse.ProtoReflect.Descriptor instead.
func (*GossipDiffResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{7}
}

func (x *GossipDiffResponse) GetEnvelope() *GossipMessageEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GossipDiffResponse) GetGossipDiffMessage() *GossipDiffMessage {
	if x != nil {
		return x.GossipDiffMessage
	}
	return nil
}

func (x *GossipDiffResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GossipDiffRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Envelope          *GossipMessageEnvelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	GossipDiffMessage *GossipDiffMessage     `protobuf:"bytes,2,opt,name=gossip_diff_message,json=gossipDiffMessage,proto3" json:"gossip_diff_message,omitempty"`
	Hash              string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // Message integrity hash
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GossipDiffRequest) Reset() {
	*x = GossipDiffRequest{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDiffRequest) ProtoMessage() {}

func (x *GossipDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDiffRequest.ProtoReflect.Descriptor instead.
func (*GossipDiffRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{8}
}

func (x *GossipDiffRequest) GetEnvelope() *GossipMessageEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GossipDiffRequest) GetGossipDiffMessage() *GossipDiffMessage {
	if x != nil {
		return x.GossipDiffMessage
	}
	return nil
}

func (x *GossipDiffRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GossipDeltaResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Envelope           *GossipMessageEnvelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	GossipDeltaMessage *GossipDeltaMessage    `protobuf:"bytes,2,opt,name=gossip_delta_message,json=gossipDeltaMessage,proto3" json:"gossip_delta_message,omitempty"` // Optional: only present if delta exists
	Hash               string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`                                                         // Message integrity hash (only present if gossip_delta_message is present)
	HasDelta           bool                   `protobuf:"varint,4,opt,name=has_delta,json=hasDelta,proto3" json:"has_delta,omitempty"`                                // Indicates whether gossip_delta_message contains data
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GossipDeltaResponse) Reset() {
	*x = GossipDeltaResponse{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDeltaResponse) ProtoMessage() {}

func (x *GossipDeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDeltaResponse.ProtoReflect.Descriptor instead.
func (*GossipDeltaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{9}
}

func (x *GossipDeltaResponse) GetEnvelope() *GossipMessageEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GossipDeltaResponse) GetGossipDeltaMessage() *GossipDeltaMessage {
	if x != nil {
		return x.GossipDeltaMessage
	}
	return nil
}

func (x *GossipDeltaResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *GossipDeltaResponse) GetHasDelta() bool {
	if x != nil {
		return x.HasDelta
	}
	return false
}

type GossipDeltaRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Envelope           *GossipMessageEnvelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	GossipDeltaMessage *GossipDeltaMessage    `protobuf:"bytes,2,opt,name=gossip_delta_message,json=gossipDeltaMessage,proto3" json:"gossip_delta_message,omitempty"`
	Hash               string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"` // Message integrity hash
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GossipDeltaRequest) Reset() {
	*x = GossipDeltaRequest{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDeltaRequest) ProtoMessage() {}

func (x *GossipDeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDeltaRequest.ProtoReflect.Descriptor instead.
func (*GossipDeltaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{10}
}

func (x *GossipDeltaRequest) GetEnvelope() *GossipMessageEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GossipDeltaRequest) GetGossipDeltaMessage() *GossipDeltaMessage {
	if x != nil {
		return x.GossipDeltaMessage
	}
	return nil
}

func (x *GossipDeltaRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GossipEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipEmptyResponse) Reset() {
	*x = GossipEmptyResponse{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipEmptyResponse) ProtoMessage() {}

func (x *GossipEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipEmptyResponse.ProtoReflect.Descriptor instead.
func (*GossipEmptyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{11}
}

var File_pkg_cluster_messages_proto protoreflect.FileDescriptor

const file_pkg_cluster_messages_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/cluster/messages.proto\"-\n" +
	"\x15GossipMessageEnvelope\x12\x14\n" +
	"\x05srcId\x18\x01 \x01(\tR\x05srcId\"\xea\x01\n" +
	"\x16GossipHeartbeatMessage\x12 \n" +
	"\fts_unix_nano\x18\x01 \x01(\x03R\n" +
	"tsUnixNano\x12[\n" +
	"\x12version_map_digest\x18\x02 \x03(\v2-.GossipHeartbeatMessage.VersionMapDigestEntryR\x10versionMapDigest\x1aQ\n" +
	"\x15VersionMapDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.DigestEntryR\x05value:\x028\x01\"\xd9\x02\n" +
	"\x11GossipDiffMessage\x12C\n" +
	"\vstate_delta\x18\x01 \x03(\v2\".GossipDiffMessage.StateDeltaEntryR\n" +
	"stateDelta\x12V\n" +
	"\x12version_map_digest\x18\x02 \x03(\v2(.GossipDiffMessage.VersionMapDigestEntryR\x10versionMapDigest\x1aT\n" +
	"\x0fStateDeltaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.GossipVersionedStateR\x05value:\x028\x01\x1aQ\n" +
	"\x15VersionMapDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.DigestEntryR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x12GossipDeltaMessage\x12D\n" +
	"\vstate_delta\x18\x01 \x03(\v2#.GossipDeltaMessage.StateDeltaEntryR\n" +
	"stateDelta\x1aT\n" +
	"\x0fStateDeltaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.GossipVersionedStateR\x05value:\x028\x01\"[\n" +
	"\x14GossipVersionedState\x12/\n" +
	"\fdigest_entry\x18\x01 \x01(\v2\f.DigestEntryR\vdigestEntry\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\x9b\x01\n" +
	"\vDigestEntry\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12-\n" +
	"\x13last_seen_unix_nano\x18\x03 \x01(\x03R\x10lastSeenUnixNano\x12)\n" +
	"\n" +
	"peer_state\x18\x04 \x01(\x0e2\n" +
	".PeerStateR\tpeerState\"\xa6\x01\n" +
	"\x16GossipHeartbeatRequest\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.GossipMessageEnvelopeR\benvelope\x12D\n" +
	"\x11heartbeat_message\x18\x02 \x01(\v2\x17.GossipHeartbeatMessageR\x10heartbeatMessage\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"\xa0\x01\n" +
	"\x12GossipDiffResponse\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.GossipMessageEnvelopeR\benvelope\x12B\n" +
	"\x13gossip_diff_message\x18\x02 \x01(\v2\x12.GossipDiffMessageR\x11gossipDiffMessage\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"\x9f\x01\n" +
	"\x11GossipDiffRequest\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.GossipMessageEnvelopeR\benvelope\x12B\n" +
	"\x13gossip_diff_message\x18\x02 \x01(\v2\x12.GossipDiffMessageR\x11gossipDiffMessage\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"\xc1\x01\n" +
	"\x13GossipDeltaResponse\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.GossipMessageEnvelopeR\benvelope\x12E\n" +
	"\x14gossip_delta_message\x18\x02 \x01(\v2\x13.GossipDeltaMessageR\x12gossipDeltaMessage\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\x12\x1b\n" +
	"\thas_delta\x18\x04 \x01(\bR\bhasDelta\"\xa3\x01\n" +
	"\x12GossipDeltaRequest\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.GossipMessageEnvelopeR\benvelope\x12E\n" +
	"\x14gossip_delta_message\x18\x02 \x01(\v2\x13.GossipDeltaMessageR\x12gossipDeltaMessage\x12\x12\n" +
	"\x04hash\x18\x03 \x01(\tR\x04hash\"\x15\n" +
	"\x13GossipEmptyResponse*s\n" +
	"\tPeerState\x12\x1a\n" +
	"\x16PEER_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PEER_STATE_HEALTHY\x10\x01\x12\x1d\n" +
	"\x19PEER_STATE_SUSPECTED_DEAD\x10\x02\x12\x13\n" +
	"\x0fPEER_STATE_DEAD\x10\x032\x84\x01\n" +
	"\rGossipService\x12=\n" +
	"\rSendHeartbeat\x12\x17.GossipHeartbeatRequest\x1a\x13.GossipDiffResponse\x124\n" +
	"\bSendDiff\x12\x12.GossipDiffRequest\x1a\x14.GossipDeltaResponseB0Z.github.com/spechtlabs/tka/pkg/cluster/messagesb\x06proto3"

var (
	file_pkg_cluster_messages_proto_rawDescOnce sync.Once
	file_pkg_cluster_messages_proto_rawDescData []byte
)

func file_pkg_cluster_messages_proto_rawDescGZIP() []byte {
	file_pkg_cluster_messages_proto_rawDescOnce.Do(func() {
		file_pkg_cluster_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cluster_messages_proto_rawDesc), len(file_pkg_cluster_messages_proto_rawDesc)))
	})
	return file_pkg_cluster_messages_proto_rawDescData
}

var file_pkg_cluster_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_cluster_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_pkg_cluster_messages_proto_goTypes = []any{
	(PeerState)(0),                 // 0: PeerState
	(*GossipMessageEnvelope)(nil),  // 1: GossipMessageEnvelope
	(*GossipHeartbeatMessage)(nil), // 2: GossipHeartbeatMessage
	(*GossipDiffMessage)(nil),      // 3: GossipDiffMessage
	(*GossipDeltaMessage)(nil),     // 4: GossipDeltaMessage
	(*GossipVersionedState)(nil),   // 5: GossipVersionedState
	(*DigestEntry)(nil),            // 6: DigestEntry
	(*GossipHeartbeatRequest)(nil), // 7: GossipHeartbeatRequest
	(*GossipDiffResponse)(nil),     // 8: GossipDiffResponse
	(*GossipDiffRequest)(nil),      // 9: GossipDiffRequest
	(*GossipDeltaResponse)(nil),    // 10: GossipDeltaResponse
	(*GossipDeltaRequest)(nil),     // 11: GossipDeltaRequest
	(*GossipEmptyResponse)(nil),    // 12: GossipEmptyResponse
	nil,                            // 13: GossipHeartbeatMessage.VersionMapDigestEntry
	nil,                            // 14: GossipDiffMessage.StateDeltaEntry
	nil,                            // 15: GossipDiffMessage.VersionMapDigestEntry
	nil,                            // 16: GossipDeltaMessage.StateDeltaEntry
}
var file_pkg_cluster_messages_proto_depIdxs = []int32{
	13, // 0: GossipHeartbeatMessage.version_map_digest:type_name -> GossipHeartbeatMessage.VersionMapDigestEntry
	14, // 1: GossipDiffMessage.state_delta:type_name -> GossipDiffMessage.StateDeltaEntry
	15, // 2: GossipDiffMessage.version_map_digest:type_name -> GossipDiffMessage.VersionMapDigestEntry
	16, // 3: GossipDeltaMessage.state_delta:type_name -> GossipDeltaMessage.StateDeltaEntry
	6,  // 4: GossipVersionedState.digest_entry:type_name -> DigestEntry
	0,  // 5: DigestEntry.peer_state:type_name -> PeerState
	1,  // 6: GossipHeartbeatRequest.envelope:type_name -> GossipMessageEnvelope
	2,  // 7: GossipHeartbeatRequest.heartbeat_message:type_name -> GossipHeartbeatMessage
	1,  // 8: GossipDiffResponse.envelope:type_name -> GossipMessageEnvelope
	3,  // 9: GossipDiffResponse.gossip_diff_message:type_name -> GossipDiffMessage
	1,  // 10: GossipDiffRequest.envelope:type_name -> GossipMessageEnvelope
	3,  // 11: GossipDiffRequest.gossip_diff_message:type_name -> GossipDiffMessage
	1,  // 12: GossipDeltaResponse.envelope:type_name -> GossipMessageEnvelope
	4,  // 13: GossipDeltaResponse.gossip_delta_message:type_name -> GossipDeltaMessage
	1,  // 14: GossipDeltaRequest.envelope:type_name -> GossipMessageEnvelope
	4,  // 15: GossipDeltaRequest.gossip_delta_message:type_name -> GossipDeltaMessage
	6,  // 16: GossipHeartbeatMessage.VersionMapDigestEntry.value:type_name -> DigestEntry
	5,  // 17: GossipDiffMessage.StateDeltaEntry.value:type_name -> GossipVersionedState
	6,  // 18: GossipDiffMessage.VersionMapDigestEntry.value:type_name -> DigestEntry
	5,  // 19: GossipDeltaMessage.StateDeltaEntry.value:type_name -> GossipVersionedState
	7,  // 20: GossipService.SendHeartbeat:input_type -> GossipHeartbeatRequest
	9,  // 21: GossipService.SendDiff:input_type -> GossipDiffRequest
	8,  // 22: GossipService.SendHeartbeat:output_type -> GossipDiffResponse
	10, // 23: GossipService.SendDiff:output_type -> GossipDeltaResponse
	22, // [22:24] is the sub-list for method output_type
	20, // [20:22] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pkg_cluster_messages_proto_init() }
func file_pkg_cluster_messages_proto_init() {
	if File_pkg_cluster_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cluster_messages_proto_rawDesc), len(file_pkg_cluster_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cluster_messages_proto_goTypes,
		DependencyIndexes: file_pkg_cluster_messages_proto_depIdxs,
		EnumInfos:         file_pkg_cluster_messages_proto_enumTypes,
		MessageInfos:      file_pkg_cluster_messages_proto_msgTypes,
	}.Build()
	File_pkg_cluster_messages_proto = out.File
	file_pkg_cluster_messages_proto_goTypes = nil
	file_pkg_cluster_messages_proto_depIdxs = nil
}
