// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: pkg/cluster/messages.proto

package messages

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GossipService_SendHeartbeat_FullMethodName = "/GossipService/SendHeartbeat"
	GossipService_SendDiff_FullMethodName      = "/GossipService/SendDiff"
)

// GossipServiceClient is the client API for GossipService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GossipServiceClient interface {
	// SendHeartbeat: Node A sends heartbeat to Node B, Node B responds with diff
	// Flow: Heartbeat → Diff
	SendHeartbeat(ctx context.Context, in *GossipHeartbeatRequest, opts ...grpc.CallOption) (*GossipDiffResponse, error)
	// SendDiff: Node A sends diff to Node B, Node B responds with delta (if any) or empty
	// Flow: Diff → Delta (or empty)
	SendDiff(ctx context.Context, in *GossipDiffRequest, opts ...grpc.CallOption) (*GossipDeltaResponse, error)
}

type gossipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGossipServiceClient(cc grpc.ClientConnInterface) GossipServiceClient {
	return &gossipServiceClient{cc}
}

func (c *gossipServiceClient) SendHeartbeat(ctx context.Context, in *GossipHeartbeatRequest, opts ...grpc.CallOption) (*GossipDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipDiffResponse)
	err := c.cc.Invoke(ctx, GossipService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gossipServiceClient) SendDiff(ctx context.Context, in *GossipDiffRequest, opts ...grpc.CallOption) (*GossipDeltaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GossipDeltaResponse)
	err := c.cc.Invoke(ctx, GossipService_SendDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GossipServiceServer is the server API for GossipService service.
// All implementations must embed UnimplementedGossipServiceServer
// for forward compatibility.
type GossipServiceServer interface {
	// SendHeartbeat: Node A sends heartbeat to Node B, Node B responds with diff
	// Flow: Heartbeat → Diff
	SendHeartbeat(context.Context, *GossipHeartbeatRequest) (*GossipDiffResponse, error)
	// SendDiff: Node A sends diff to Node B, Node B responds with delta (if any) or empty
	// Flow: Diff → Delta (or empty)
	SendDiff(context.Context, *GossipDiffRequest) (*GossipDeltaResponse, error)
	mustEmbedUnimplementedGossipServiceServer()
}

// UnimplementedGossipServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGossipServiceServer struct{}

func (UnimplementedGossipServiceServer) SendHeartbeat(context.Context, *GossipHeartbeatRequest) (*GossipDiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedGossipServiceServer) SendDiff(context.Context, *GossipDiffRequest) (*GossipDeltaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDiff not implemented")
}
func (UnimplementedGossipServiceServer) mustEmbedUnimplementedGossipServiceServer() {}
func (UnimplementedGossipServiceServer) testEmbeddedByValue()                       {}

// UnsafeGossipServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GossipServiceServer will
// result in compilation errors.
type UnsafeGossipServiceServer interface {
	mustEmbedUnimplementedGossipServiceServer()
}

func RegisterGossipServiceServer(s grpc.ServiceRegistrar, srv GossipServiceServer) {
	// If the following call pancis, it indicates UnimplementedGossipServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GossipService_ServiceDesc, srv)
}

func _GossipService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).SendHeartbeat(ctx, req.(*GossipHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GossipService_SendDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).SendDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GossipService_SendDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).SendDiff(ctx, req.(*GossipDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GossipService_ServiceDesc is the grpc.ServiceDesc for GossipService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GossipService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GossipService",
	HandlerType: (*GossipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _GossipService_SendHeartbeat_Handler,
		},
		{
			MethodName: "SendDiff",
			Handler:    _GossipService_SendDiff_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/cluster/messages.proto",
}
