// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pkg/cluster/messages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GossipMessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcId         string                 `protobuf:"bytes,1,opt,name=srcId,proto3" json:"srcId,omitempty"`
	AnswerPort    string                 `protobuf:"bytes,2,opt,name=answerPort,proto3" json:"answerPort,omitempty"`
	Traceparent   string                 `protobuf:"bytes,3,opt,name=traceparent,proto3" json:"traceparent,omitempty"` // W3C Trace Context traceparent header for distributed tracing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessageEnvelope) Reset() {
	*x = GossipMessageEnvelope{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessageEnvelope) ProtoMessage() {}

func (x *GossipMessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessageEnvelope.ProtoReflect.Descriptor instead.
func (*GossipMessageEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GossipMessageEnvelope) GetSrcId() string {
	if x != nil {
		return x.SrcId
	}
	return ""
}

func (x *GossipMessageEnvelope) GetAnswerPort() string {
	if x != nil {
		return x.AnswerPort
	}
	return ""
}

func (x *GossipMessageEnvelope) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

type GossipMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Envelope *GossipMessageEnvelope `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	// Types that are valid to be assigned to Message:
	//
	//	*GossipMessage_HeartbeatMessage
	//	*GossipMessage_GossipDiffMessage
	//	*GossipMessage_GossipDeltaMessage
	Message       isGossipMessage_Message `protobuf_oneof:"message"`
	Hash          string                  `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GossipMessage) GetEnvelope() *GossipMessageEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *GossipMessage) GetMessage() isGossipMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GossipMessage) GetHeartbeatMessage() *GossipHeartbeatMessage {
	if x != nil {
		if x, ok := x.Message.(*GossipMessage_HeartbeatMessage); ok {
			return x.HeartbeatMessage
		}
	}
	return nil
}

func (x *GossipMessage) GetGossipDiffMessage() *GossipDiffMessage {
	if x != nil {
		if x, ok := x.Message.(*GossipMessage_GossipDiffMessage); ok {
			return x.GossipDiffMessage
		}
	}
	return nil
}

func (x *GossipMessage) GetGossipDeltaMessage() *GossipDeltaMessage {
	if x != nil {
		if x, ok := x.Message.(*GossipMessage_GossipDeltaMessage); ok {
			return x.GossipDeltaMessage
		}
	}
	return nil
}

func (x *GossipMessage) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type isGossipMessage_Message interface {
	isGossipMessage_Message()
}

type GossipMessage_HeartbeatMessage struct {
	HeartbeatMessage *GossipHeartbeatMessage `protobuf:"bytes,2,opt,name=heartbeat_message,json=heartbeatMessage,proto3,oneof"`
}

type GossipMessage_GossipDiffMessage struct {
	GossipDiffMessage *GossipDiffMessage `protobuf:"bytes,3,opt,name=gossip_diff_message,json=gossipDiffMessage,proto3,oneof"`
}

type GossipMessage_GossipDeltaMessage struct {
	GossipDeltaMessage *GossipDeltaMessage `protobuf:"bytes,4,opt,name=gossip_delta_message,json=gossipDeltaMessage,proto3,oneof"`
}

func (*GossipMessage_HeartbeatMessage) isGossipMessage_Message() {}

func (*GossipMessage_GossipDiffMessage) isGossipMessage_Message() {}

func (*GossipMessage_GossipDeltaMessage) isGossipMessage_Message() {}

type GossipHeartbeatMessage struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	TsUnixNano       int64                   `protobuf:"varint,1,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	VersionMapDigest map[string]*DigestEntry `protobuf:"bytes,2,rep,name=version_map_digest,json=versionMapDigest,proto3" json:"version_map_digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GossipHeartbeatMessage) Reset() {
	*x = GossipHeartbeatMessage{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipHeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipHeartbeatMessage) ProtoMessage() {}

func (x *GossipHeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipHeartbeatMessage.ProtoReflect.Descriptor instead.
func (*GossipHeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GossipHeartbeatMessage) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

func (x *GossipHeartbeatMessage) GetVersionMapDigest() map[string]*DigestEntry {
	if x != nil {
		return x.VersionMapDigest
	}
	return nil
}

type GossipDiffMessage struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	StateDelta       map[string]*GossipVersionedState `protobuf:"bytes,1,rep,name=state_delta,json=stateDelta,proto3" json:"state_delta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	VersionMapDigest map[string]*DigestEntry          `protobuf:"bytes,2,rep,name=version_map_digest,json=versionMapDigest,proto3" json:"version_map_digest,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GossipDiffMessage) Reset() {
	*x = GossipDiffMessage{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDiffMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDiffMessage) ProtoMessage() {}

func (x *GossipDiffMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDiffMessage.ProtoReflect.Descriptor instead.
func (*GossipDiffMessage) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{3}
}

func (x *GossipDiffMessage) GetStateDelta() map[string]*GossipVersionedState {
	if x != nil {
		return x.StateDelta
	}
	return nil
}

func (x *GossipDiffMessage) GetVersionMapDigest() map[string]*DigestEntry {
	if x != nil {
		return x.VersionMapDigest
	}
	return nil
}

type GossipDeltaMessage struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	StateDelta    map[string]*GossipVersionedState `protobuf:"bytes,1,rep,name=state_delta,json=stateDelta,proto3" json:"state_delta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipDeltaMessage) Reset() {
	*x = GossipDeltaMessage{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipDeltaMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipDeltaMessage) ProtoMessage() {}

func (x *GossipDeltaMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipDeltaMessage.ProtoReflect.Descriptor instead.
func (*GossipDeltaMessage) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{4}
}

func (x *GossipDeltaMessage) GetStateDelta() map[string]*GossipVersionedState {
	if x != nil {
		return x.StateDelta
	}
	return nil
}

type GossipVersionedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DigestEntry   *DigestEntry           `protobuf:"bytes,1,opt,name=digest_entry,json=digestEntry,proto3" json:"digest_entry,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipVersionedState) Reset() {
	*x = GossipVersionedState{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipVersionedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipVersionedState) ProtoMessage() {}

func (x *GossipVersionedState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipVersionedState.ProtoReflect.Descriptor instead.
func (*GossipVersionedState) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{5}
}

func (x *GossipVersionedState) GetDigestEntry() *DigestEntry {
	if x != nil {
		return x.DigestEntry
	}
	return nil
}

func (x *GossipVersionedState) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DigestEntry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Version          uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Address          string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	LastSeenUnixNano int64                  `protobuf:"varint,3,opt,name=last_seen_unix_nano,json=lastSeenUnixNano,proto3" json:"last_seen_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DigestEntry) Reset() {
	*x = DigestEntry{}
	mi := &file_pkg_cluster_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigestEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigestEntry) ProtoMessage() {}

func (x *DigestEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cluster_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigestEntry.ProtoReflect.Descriptor instead.
func (*DigestEntry) Descriptor() ([]byte, []int) {
	return file_pkg_cluster_messages_proto_rawDescGZIP(), []int{6}
}

func (x *DigestEntry) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DigestEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DigestEntry) GetLastSeenUnixNano() int64 {
	if x != nil {
		return x.LastSeenUnixNano
	}
	return 0
}

var File_pkg_cluster_messages_proto protoreflect.FileDescriptor

const file_pkg_cluster_messages_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/cluster/messages.proto\"o\n" +
	"\x15GossipMessageEnvelope\x12\x14\n" +
	"\x05srcId\x18\x01 \x01(\tR\x05srcId\x12\x1e\n" +
	"\n" +
	"answerPort\x18\x02 \x01(\tR\n" +
	"answerPort\x12 \n" +
	"\vtraceparent\x18\x03 \x01(\tR\vtraceparent\"\xb9\x02\n" +
	"\rGossipMessage\x122\n" +
	"\benvelope\x18\x01 \x01(\v2\x16.GossipMessageEnvelopeR\benvelope\x12F\n" +
	"\x11heartbeat_message\x18\x02 \x01(\v2\x17.GossipHeartbeatMessageH\x00R\x10heartbeatMessage\x12D\n" +
	"\x13gossip_diff_message\x18\x03 \x01(\v2\x12.GossipDiffMessageH\x00R\x11gossipDiffMessage\x12G\n" +
	"\x14gossip_delta_message\x18\x04 \x01(\v2\x13.GossipDeltaMessageH\x00R\x12gossipDeltaMessage\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hashB\t\n" +
	"\amessage\"\xea\x01\n" +
	"\x16GossipHeartbeatMessage\x12 \n" +
	"\fts_unix_nano\x18\x01 \x01(\x03R\n" +
	"tsUnixNano\x12[\n" +
	"\x12version_map_digest\x18\x02 \x03(\v2-.GossipHeartbeatMessage.VersionMapDigestEntryR\x10versionMapDigest\x1aQ\n" +
	"\x15VersionMapDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.DigestEntryR\x05value:\x028\x01\"\xd9\x02\n" +
	"\x11GossipDiffMessage\x12C\n" +
	"\vstate_delta\x18\x01 \x03(\v2\".GossipDiffMessage.StateDeltaEntryR\n" +
	"stateDelta\x12V\n" +
	"\x12version_map_digest\x18\x02 \x03(\v2(.GossipDiffMessage.VersionMapDigestEntryR\x10versionMapDigest\x1aT\n" +
	"\x0fStateDeltaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.GossipVersionedStateR\x05value:\x028\x01\x1aQ\n" +
	"\x15VersionMapDigestEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.DigestEntryR\x05value:\x028\x01\"\xb0\x01\n" +
	"\x12GossipDeltaMessage\x12D\n" +
	"\vstate_delta\x18\x01 \x03(\v2#.GossipDeltaMessage.StateDeltaEntryR\n" +
	"stateDelta\x1aT\n" +
	"\x0fStateDeltaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.GossipVersionedStateR\x05value:\x028\x01\"[\n" +
	"\x14GossipVersionedState\x12/\n" +
	"\fdigest_entry\x18\x01 \x01(\v2\f.DigestEntryR\vdigestEntry\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"p\n" +
	"\vDigestEntry\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12-\n" +
	"\x13last_seen_unix_nano\x18\x03 \x01(\x03R\x10lastSeenUnixNanoB\x16Z\x14pkg/cluster/messagesb\x06proto3"

var (
	file_pkg_cluster_messages_proto_rawDescOnce sync.Once
	file_pkg_cluster_messages_proto_rawDescData []byte
)

func file_pkg_cluster_messages_proto_rawDescGZIP() []byte {
	file_pkg_cluster_messages_proto_rawDescOnce.Do(func() {
		file_pkg_cluster_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cluster_messages_proto_rawDesc), len(file_pkg_cluster_messages_proto_rawDesc)))
	})
	return file_pkg_cluster_messages_proto_rawDescData
}

var file_pkg_cluster_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_cluster_messages_proto_goTypes = []any{
	(*GossipMessageEnvelope)(nil),  // 0: GossipMessageEnvelope
	(*GossipMessage)(nil),          // 1: GossipMessage
	(*GossipHeartbeatMessage)(nil), // 2: GossipHeartbeatMessage
	(*GossipDiffMessage)(nil),      // 3: GossipDiffMessage
	(*GossipDeltaMessage)(nil),     // 4: GossipDeltaMessage
	(*GossipVersionedState)(nil),   // 5: GossipVersionedState
	(*DigestEntry)(nil),            // 6: DigestEntry
	nil,                            // 7: GossipHeartbeatMessage.VersionMapDigestEntry
	nil,                            // 8: GossipDiffMessage.StateDeltaEntry
	nil,                            // 9: GossipDiffMessage.VersionMapDigestEntry
	nil,                            // 10: GossipDeltaMessage.StateDeltaEntry
}
var file_pkg_cluster_messages_proto_depIdxs = []int32{
	0,  // 0: GossipMessage.envelope:type_name -> GossipMessageEnvelope
	2,  // 1: GossipMessage.heartbeat_message:type_name -> GossipHeartbeatMessage
	3,  // 2: GossipMessage.gossip_diff_message:type_name -> GossipDiffMessage
	4,  // 3: GossipMessage.gossip_delta_message:type_name -> GossipDeltaMessage
	7,  // 4: GossipHeartbeatMessage.version_map_digest:type_name -> GossipHeartbeatMessage.VersionMapDigestEntry
	8,  // 5: GossipDiffMessage.state_delta:type_name -> GossipDiffMessage.StateDeltaEntry
	9,  // 6: GossipDiffMessage.version_map_digest:type_name -> GossipDiffMessage.VersionMapDigestEntry
	10, // 7: GossipDeltaMessage.state_delta:type_name -> GossipDeltaMessage.StateDeltaEntry
	6,  // 8: GossipVersionedState.digest_entry:type_name -> DigestEntry
	6,  // 9: GossipHeartbeatMessage.VersionMapDigestEntry.value:type_name -> DigestEntry
	5,  // 10: GossipDiffMessage.StateDeltaEntry.value:type_name -> GossipVersionedState
	6,  // 11: GossipDiffMessage.VersionMapDigestEntry.value:type_name -> DigestEntry
	5,  // 12: GossipDeltaMessage.StateDeltaEntry.value:type_name -> GossipVersionedState
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_pkg_cluster_messages_proto_init() }
func file_pkg_cluster_messages_proto_init() {
	if File_pkg_cluster_messages_proto != nil {
		return
	}
	file_pkg_cluster_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*GossipMessage_HeartbeatMessage)(nil),
		(*GossipMessage_GossipDiffMessage)(nil),
		(*GossipMessage_GossipDeltaMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cluster_messages_proto_rawDesc), len(file_pkg_cluster_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_cluster_messages_proto_goTypes,
		DependencyIndexes: file_pkg_cluster_messages_proto_depIdxs,
		MessageInfos:      file_pkg_cluster_messages_proto_msgTypes,
	}.Build()
	File_pkg_cluster_messages_proto = out.File
	file_pkg_cluster_messages_proto_goTypes = nil
	file_pkg_cluster_messages_proto_depIdxs = nil
}
