# golangci-lint configuration with TKA-specific analyzers
# This extends the base .golangci.yml with custom checks
#
# Usage:
#   golangci-lint run -c .golangci-tka.yaml ./...
#
# Or merge into your existing .golangci.yml

run:
  timeout: 5m
  tests: true
  go: "1.25"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # Standard high-value linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional quality linters
    - bodyclose
    - dupl
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - revive
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  # Error handling
  errorlint:
    errorf: true
    asserts: true
    comparison: true

  # Complexity thresholds
  gocyclo:
    min-complexity: 15

  # Function length
  funlen:
    lines: 60
    statements: 40

  # Duplicate detection
  dupl:
    threshold: 100

  # Security checks
  gosec:
    excludes:
      - G104 # Audit errors not checked (we use humane errors)
    config:
      G301: "0750" # File permissions
      G302: "0640"
      G306: "0640"

  # Code review comments
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  # gocritic checks
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - hugeParam # We use options pattern which can have larger structs
      - rangeValCopy

issues:
  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - funlen

    # Exclude mock packages from most checks
    - path: /mock/
      linters:
        - dupl
        - unused
        - gocritic

    # Exclude generated files
    - path: zz_generated
      linters:
        - all

    # Allow fmt.Errorf in tests
    - path: _test\.go
      text: "fmt.Errorf"

  exclude-dirs:
    - vendor
    - third_party
    - testdata
    - tools/analyzers/*/testdata

  max-issues-per-linter: 50
  max-same-issues: 3

severity:
  default-severity: warning
  rules:
    - linters:
        - revive
      severity: info
    - linters:
        - gosec
      severity: error
