version: 2

project_name: tailscale-k8s-auth

builds:
  - id: server
    env: &env
      - CGO_ENABLED=0
    goos: &srv_goos
      - linux
    goarch: &goarch
      - arm64
      - amd64
    goarm: &goarm
      - "7"
    binary: ts-k8s-srv
    dir: ./cmd/server/
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags: &ldflags
      - -X=github.com/spechtlabs/tka/pkg/cmd.Version={{.Version}}
      - -X=github.com/spechtlabs/tka/pkg/cmd.Commit={{.Commit}}
      - -X=github.com/spechtlabs/tka/pkg/cmd.Date={{ .CommitDate }}

  - id: cli
    env: *env
    goos:
      - linux
      - windows
      - darwin
    goarch: *goarch
    goarm: *goarm
    binary: ts-k8s-auth
    dir: ./cmd/cli/
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags: *ldflags

# Docker image for server (multi-platform)
dockers:
  - id: oci-bundle
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: amd64
    ids:
      - server
    image_templates:
      - ghcr.io/spechtlabs/tka:latest-amd64
      - ghcr.io/spechtlabs/tka:{{ .Tag }}-amd64
      - ghcr.io/spechtlabs/tka:v{{ .Major }}-amd64
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
      - "--pull"

  - id: oci-bundle-arm64
    use: buildx
    dockerfile: Dockerfile
    goos: linux
    goarch: arm64
    ids:
      - server
    image_templates:
      - ghcr.io/spechtlabs/tka:latest-arm64
      - ghcr.io/spechtlabs/tka:{{ .Tag }}-arm64
      - ghcr.io/spechtlabs/tka:v{{ .Major }}-arm64
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
      - "--pull"

docker_manifests:
  - name_template: ghcr.io/spechtlabs/tka:latest
    image_templates:
      - ghcr.io/spechtlabs/tka:latest-amd64
      - ghcr.io/spechtlabs/tka:latest-arm64
    skip_push: auto

  - name_template: ghcr.io/spechtlabs/tka:{{ .Tag }}
    image_templates:
      - ghcr.io/spechtlabs/tka:{{ .Tag }}-amd64
      - ghcr.io/spechtlabs/tka:{{ .Tag }}-arm64
    skip_push: auto

  - name_template: ghcr.io/spechtlabs/tka:v{{ .Major }}
    image_templates:
      - ghcr.io/spechtlabs/tka:v{{ .Major }}-amd64
      - ghcr.io/spechtlabs/tka:v{{ .Major }}-arm64
    skip_push: auto

# Sign docker-image with cosign (keyless)
docker_signs:
  - id: oci-bundle-sign
    artifacts: manifests
    args:
    - "sign"
    - --oidc-issuer=https://token.actions.githubusercontent.com
    - "${artifact}"
    - --yes

# Sign everything else
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --yes
      - --oidc-issuer=https://token.actions.githubusercontent.com
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: binary

# Regular OS packages (for now only systemd based OSes)
nfpms:
  - id: cli
    package_name: tka
    ids:
      - cli
    maintainer: Cedric Specht <cedric@specht-labs.de>
    description: tka is a CLI tool for tailscale-k8s-auth, a tailnet-native Kubernetes access system. It allows users to securely log in to Kubernetes clusters using their Tailscale identity, receiving short-lived, auto-expiring kubeconfigs with scoped permissions.
    homepage: https://tka.specht-labs.de
    vendor: Specht Labs
    license: Apache 2.0
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin

archives:
  - id: server
    ids:
      - server
    name_template: 'tailscale-k8s-auth_server_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

  - id: cli
    ids:
      - cli
    name_template: 'tailscale-k8s-auth_cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
