// Package swagger GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Specht Labs",
            "url": "specht-labs.de",
            "email": "tka@specht-labs.de"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1alpha1/kubeconfig": {
            "get": {
                "security": [
                    {
                        "TailscaleAuth": []
                    }
                ],
                "description": "Generates and returns a kubeconfig file for the authenticated Tailscale user",
                "produces": [
                    "application/yaml",
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Get kubeconfig for authenticated user",
                "responses": {
                    "200": {
                        "description": "OK - Returns kubeconfig file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Tagged nodes not supported or error unmarshaling capability or multiple capability rules",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Request from Funnel or no capability rule found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found - User not authenticated or credentials not ready",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Error with WhoIs or generating kubeconfig",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1alpha1/login": {
            "get": {
                "security": [
                    {
                        "TailscaleAuth": []
                    }
                ],
                "description": "Retrieves the current authentication status for a Tailscale user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Get user authentication status",
                "responses": {
                    "200": {
                        "description": "OK - Returns the current user authentication status",
                        "schema": {
                            "$ref": "#/definitions/models.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Tagged nodes not supported or error unmarshaling capability or multiple capability rules",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Request from Funnel or no capability rule found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Error with WhoIs or retrieving user status",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TailscaleAuth": []
                    }
                ],
                "description": "Authenticates a user through Tailscale, validates their capability rule, and provisions Kubernetes credentials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Authenticate user and provision Kubernetes credentials",
                "responses": {
                    "202": {
                        "description": "Accepted - User authenticated and credentials are being provisioned",
                        "schema": {
                            "$ref": "#/definitions/models.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Tagged nodes not supported or error unmarshaling capability or multiple capability rules",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Request from Funnel or no capability rule found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity - Invalid capability rule (period too short)",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Error with WhoIs, parsing duration, or signing in user",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1alpha1/logout": {
            "post": {
                "security": [
                    {
                        "TailscaleAuth": []
                    }
                ],
                "description": "Revokes Kubernetes credentials for the authenticated Tailscale user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Log out authenticated user",
                "responses": {
                    "200": {
                        "description": "OK - User successfully logged out with login info",
                        "schema": {
                            "$ref": "#/definitions/models.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Tagged nodes not supported or error unmarshaling capability or multiple capability rules",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Request from Funnel or no capability rule found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found - User not authenticated",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Error with WhoIs, parsing duration, or during logout process",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orchestrator/v1alpha1/clusters": {
            "get": {
                "security": [
                    {
                        "TailscaleAuth": []
                    }
                ],
                "description": "Lists all clusters that the user has access to",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "List all clusters that the user has access to",
                "responses": {
                    "200": {
                        "description": "A list of clusters that the user has access to",
                        "schema": {
                            "$ref": "#/definitions/models.ClusterListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Tagged nodes not supported or error unmarshaling capability or multiple capability rules",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Request from Funnel or no capability rule found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Error with WhoIs, parsing duration, or signing in user",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TailscaleAuth": []
                    }
                ],
                "description": "Registers a new cluster with the orchestrator",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orchestrator"
                ],
                "summary": "Register a new cluster",
                "parameters": [
                    {
                        "description": "Cluster to register",
                        "name": "cluster",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ClusterListItem"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully registered cluster",
                        "schema": {
                            "$ref": "#/definitions/models.ClusterListItem"
                        }
                    },
                    "400": {
                        "description": "Bad Request - Invalid request body or validation errors",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Request from Funnel or no capability rule found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error - Error processing the request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ClusterListItem": {
            "description": "Contains the details of a single cluster",
            "type": "object",
            "properties": {
                "api_endpoint": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ClusterListResponse": {
            "description": "Contains a list of clusters that the user has access to",
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ClusterListItem"
                    }
                }
            }
        },
        "models.ErrorResponse": {
            "description": "Structured error response with contextual advice",
            "type": "object",
            "properties": {
                "advice": {
                    "description": "List of suggestions to help resolve the error\nexample: [\"Check your Tailscale connection\", \"Verify you have the required capabilities\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "Primary error message\nexample: Failed to authenticate user",
                    "type": "string"
                }
            }
        },
        "models.UserLoginResponse": {
            "description": "Contains authenticated user information and session details",
            "type": "object",
            "properties": {
                "role": {
                    "description": "Role assigned to the user in Kubernetes\nexample: cluster-admin",
                    "type": "string"
                },
                "until": {
                    "description": "Expiration timestamp of the authentication credentials in RFC3339 format\nexample: 2023-12-31T23:59:59Z",
                    "type": "string"
                },
                "username": {
                    "description": "Username of the authenticated user\nexample: alice@example.com",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "TailscaleAuth": {
            "description": "Authentication happens automatically via the Tailscale network. The server performs a WhoIs lookup on the client's IP address to determine identity. This header is for documentation purposes only and is not actually required to be set.",
            "type": "apiKey",
            "name": "X-Tailscale-User",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1alpha1",
	Schemes:          []string{},
	Title:            "Tailscale Kubernetes Auth API",
	Description:      "API for authenticating and authorizing Kubernetes access via Tailscale identity.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
